### Data Encoding 

In [3]:
# label encoding
# 범주형 데이터를 특정 숫자로 바꾸는 경우. 대신 숫자의 크기 때문에 모델에서 weight 값을 다르게 줄 수 있음 주의
from sklearn.preprocessing import LabelEncoder

items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print("transformed encoder: ", labels)

transformed encoder:  [0 1 4 5 3 3 2 2]


In [4]:
print('encoding class: ', encoder.classes_)

encoding class:  ['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']


In [5]:
# inverse encoding
print('origin data: ', encoder.inverse_transform([4,2,2,3,1,0]))

origin data:  ['전자렌지' '믹서' '믹서' '선풍기' '냉장고' 'TV']


### One Hot Encoding

In [10]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

# 2차원 데이터로 변환해야함
items = np.array(items).reshape(-1, 1)

# One Hot Encoding 적용
ohe = OneHotEncoder()
ohe.fit(items)
oh_label = ohe.transform(items)

print(oh_label.toarray())
print(oh_label.shape)
# 8개의 item을 원핫 인코딩을 통해 우위없이 범주형 데이터를 인코딩

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
(8, 6)


In [11]:
# 더 쉽게 구현하기 get_dummies(items)
import pandas as pd

# DataFrame을 만들어 줄 때 딕셔너리 형태로 넣어주기
df = pd.DataFrame({'items':['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']})
pd.get_dummies(df)

items_TV  items_냉장고  items_믹서  items_선풍기  items_전자렌지  items_컴퓨터
0         1          0         0          0           0          0
1         0          1         0          0           0          0
2         0          0         0          0           1          0
3         0          0         0          0           0          1
4         0          0         0          1           0          0
5         0          0         0          1           0          0
6         0          0         1          0           0          0
7         0          0         1          0           0          0

### Feature Scaling

In [16]:
# StandardScale
# 평균이 0, 분산이 1인 정규 분포 형태로 변환
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
import pandas as pd

# 붓꽃 데이터 로딩 하고 DataFrame으로 변형
iris = load_iris()
iris_df = pd.DataFrame(iris.data, columns=iris.feature_names)
print(iris_df.mean())
print(iris_df.var())
print('---------Scaled--------')

scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
iris_scaled_df = pd.DataFrame(iris_scaled, columns=iris.feature_names)
print(iris_scaled_df.mean())
print(iris_scaled_df.var())
# scale 후에 -1 ~ 1 사이의 값으로 스케일링 된 것을 볼 수 있음

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64
---------Scaled--------
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


In [17]:
# MinMaxScaler
# 데이터 값을 0과 1사이의 범위 값으로 변환 (음수 값이 있으면 -1에서 1로 변환)
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_scaled_df = pd.DataFrame(iris_scaled, columns=iris.feature_names)
print(iris_scaled_df.min())
print(iris_scaled_df.max())

sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


In [18]:
# Scaler를 이용하여 학습 데이터와 테스트 데이터와 fit(), transform(), fit_transform() 적용시 유의 점
from sklearn.preprocessing import MinMaxScaler
import numpy as np

# train data : 0 ~ 10
# test data : 0 ~ 5
# Scaler 클래스의 fit, transform()은 2차원 이상 데이터만 가능하므로 reshape(-1,1)로 차원 변경

train_array = np.arange(0, 11).reshape(-1, 1)
test_array = np.arange(0, 6).reshape(-1, 1)

In [20]:
# 최소값 0, 최대값 1로 변환하는 MinMax 객체 생성
scaler = MinMaxScaler()
scaler.fit(train_array)
train_scaled = scaler.transform(train_array)
print(train_array.reshape(-1))
print(train_scaled.reshape(-1))


[ 0  1  2  3  4  5  6  7  8  9 10]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [21]:
# 앞에서 생성한 test array를 MinMax로 따로 인코딩 하면?
scaler = MinMaxScaler()
scaler.fit(test_array)
test_scaled = scaler.transform(test_array)

print(test_array.reshape(-1))
print(test_scaled.reshape(-1))
# 실제로 5는 0.5로 트레이닝 시켰는데 결과적으로 test data 에서는 5가 1.0으로 변환됨!

[0 1 2 3 4 5]
[0.  0.2 0.4 0.6 0.8 1. ]


In [ ]:
# 스케일링을 할 땐 전체 데이터에 대해서 한번에 해줘야함